### PR TITLE
Breaking Change: Use RainLab Extensions instead of overriding User model

### PR DESCRIPTION
**Pull request by RomainMazB**
Hi @tobias-kuendig ,
For a personal use, I needed to create a similar plugin for Backend User.
So I've looked into your plugin to understand how you've done.

Then I tried to play with some tricks and I think I've found a way to increase the plugin's quality, by using [Rain Extensions](https://github.com/octobercms/library/tree/549895c8a6368b397d01fbc358b055cb40a08ed4/src/Extension) instead of overriding User, AuthManager and Cashier's Billable trait.

To thanks OFFLINE for the job made all over the OC community with the free plugins: I've spent some time to implement my way into your plugin, feel free to review, I didn't have a huge test installation: I've just installed a fresh OC with Vanilla theme and your plugin, created a dummy plugin to listen to the payment event and create the subscription using the RainLab model and then printed some invoices.

Due to the fact the plugin doesn't have anymore to override RainLab.User models, this PR is definitely a breaking change. But in the other hand this will fix:
- #9 #10 because we don't override RainLab models anymore
- #11 because Cashier is updated
- #17 because this one was caused by [a recent Stripe update](https://stripe.com/docs/upgrades#2020-08-27): now the API doesn't provide subscriptions and sources as default, we need to explicitly ask for them. Since we can't use a higher version of Cashier where this has been patched, we need to locally patch this. This has been discussed [here](https://github.com/laravel/cashier-stripe/issues/381), [here](https://github.com/laravel/cashier-stripe/issues/1033), and probably elsewhere. I've patched this issue in my personal plugin and fixed yours too.

The fact the plugin will now be more agnostic about Billable trait and RainLab User will probably save the repository from some other issue.

I've fixed some minor other issues, added the french translation and made some code cleanup. I tried to split the PR into many concise commit to be more readable.

I've created [a working repo](https://github.com/RomainMazB/oc-cashier-fix) using this patch. All you need to do is modify the .env I voluntarily committed and add you Stripe keys, secret and plan_id [used here](https://github.com/RomainMazB/oc-cashier-fix/blob/main/plugins/sunlab/cashiertest/Plugin.php#L33-L45) to confirm any other marketplace's plugin could create subscription on the RainLab.User model.

The Stripe Element form is on the `/pay` page and the invoices on `/invoices`

Hope you'll enjoy :)

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Thank you very much @RomainMazB for this PR! This looks like it was a lot of work.

> Due to the fact the plugin doesn't have anymore to override RainLab.User models, this PR is definitely a breaking change.

I see no reason against a breaking v2.0 version of the plugin. It wasn't properly designed in the first place and has also been neglected from our side because we do not use it in many projects. 

Also, having everything updated to be up to date with latest dependencies is a big plus.

I'll need some time to review and test the changes. But I'm positive that we will incorporate these changes.

Thanks again!

**Comment by RomainMazB** [comment]
It was a pleasure to help. Most of the work was done for my personal use on backend and then ported to this plugin so don't worry about the time I've spent on it: it was well deserved for all the free plugins you've created and I'm actually using.

If you need some additional work about this PR, just ask. I'll watch the repo to stay up with the update and eventual needed fixes.

**Comment by damsfx** [comment]
Any news for this PR!?

**Comment by tobias-kuendig** [comment]
@damsfx I'll take a  look at it soon (I'll keep this tab open to remind me). In the mean time you are welcome to test the PR if you need its functionality!

**Comment by tobias-kuendig** [comment]
This is released as v2, thanks again @RomainMazB for the work on this :clap:!

**Pull request merged**
